# Generated by Django 4.1.6 on 2023-03-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=1024)),
                ('contact', models.EmailField(max_length=254)),
                ('pic', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Places',
        ),
    ]
