# Generated by Django 4.1.6 on 2023-03-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_packages_delete_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('raiting', models.CharField(max_length=55)),
            ],
        ),
        migrations.AddField(
            model_name='packages',
            name='places',
            field=models.ManyToManyField(to='base.places'),
        ),
    ]
